### ISSUE TITLE
Smallest real representable difference

### ISSUE THREAD

**Issue by tuncaen** [szaghi/PENF#21]
Hi, 

I was using the parameter ` ZeroR8P ` for the comparison purpose of two real values. Lately, I updated source files and realized the change in the definition of the parameter. In the previous version of PENF, the definition was,

`real(R8P),  parameter :: ZeroR8P  = nearest(1._R8P, 1._R8P) - nearest(1._R8P,-1._R8P) `

and I was using the parameter to compare the reals as

`if ( abs( a - b ) < ZeroR8P ) then `

However, the latest version is defining the `ZeroR8P` as, 

`real(R8P),  parameter :: ZeroR8P  = 0._R8P` 

and the comparison fails. I wonder the reason behind this change. Was the previous version causing a bug?

**Comment by szaghi** [comment]
Hi @tuncaen 

I am very sorry for the uncommented change. The definition of Zero was modified because I need to use penf with Cuda Fortran and that stupid compiler does not support the previous definition.

Because the last definition is simply wrong and not useful at all, I suggest to use the previous commit: for the moment I need to use this fake definition for Cuda, but as soon as possible I will re-integrate the correct definition of Zero (maybe I will add a cpp flag just for Cuda Fortran).

**Comment by tuncaen** [comment]
Hi @szaghi, thank you for the clarification.
